### ISSUE TITLE
Rendering `schemas/modules/*.exp` resulting in file name errors

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/suma#22]
```
[suma] Current directory: ~/src/mn/iso-10303, writing schemas-sml.yml...
[suma] Compiling schema collection...
[suma] Save plain schema: plain_schemas/modules/Event_arm/Event_arm.exp
[suma] Loaded EXPRESS schema: ~/src/mn/iso-10303/schemas/modules/event/arm.exp
[suma] Save plain schema: plain_schemas/modules/Event_mim/Event_mim.exp
[suma] Loaded EXPRESS schema: ~/src/mn/iso-10303/schemas/modules/event/mim.exp
[suma] Save schema config: schema_docs/Event_arm/schema_Event_arm.yaml
[suma] Writing ~/src/mn/iso-10303/schema_docs/Event_arm/schema_Event_arm.yaml...
[suma] Done.
[suma] Save EXPRESS adoc: schema_docs/Event_arm/doc_Event_arm.adoc
```

The generated `plain_schemas/.../*.exp` filenames are wrong.

The schemas need to keep their original file names, not using the schema names in the `*.exp` file. 

For example, in `documents/iso-10303-1064/`.

In the `schemas.yaml`:
```yaml
---
schemas:
  Event_arm:
    path: ../../schemas/modules/event/arm.exp
  Event_mim:
    path: ../../schemas/modules/event/mim.exp
```

In the `collection.yaml`:
```yaml
manifest:
  level: collection
  title: ISO Collection
  docref:
    - level: document
      title: Document
      docref:
        - fileref: document.adoc
    - level: attachments
      title: Attachments
      docref:
        - fileref: ../../plain_schemas/modules/event/arm.exp
          identifier: arm.exp
          attachment: true
        - fileref: ../../schema_docs/Event_arm/doc_Event_arm.html
          identifier: Event_arm.html
          attachment: true
        - fileref: ../../plain_schemas/modules/event/mim.exp
          identifier: mim.exp
          attachment: true
        - fileref: ../../schema_docs/Event_mim/doc_Event_mim.html
          identifier: Event_mim.html
          attachment: true
```

These names in `collection.yaml` need to match the files generated by Suma.
